Redmine Scmacros
================
Gregory ROMÉ, Mitsuhiro YOSHITANI
v0.2.0, 02-oct-2013

Copyright (C) 2010-2013 Gregory ROMÉ
Copyright (C) 2011 Mitsuhiro YOSHITANI

This plugin provides Wiki macros related to repositories.

License
-------

--------------------------------------------------------------------------------
Copyright (C) 2010-2013 Gregory ROMÉ
Copyright (C) 2011 Mitsuhiro YOSHITANI

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
--------------------------------------------------------------------------------

Installation
------------

See redmine plugin installation howto.

This plugin does not modify the database.

Required
--------

Redmine 1.3.0 later

https://github.com/asciidoctor/asciidoctor[Asciidoctor]

Documentation
-------------

To include a repository file:

-------------------------------
{{repo_include(file_path)}}

{{repo_include(file_path, revision)}}

{{repo_includewiki(file_path)}}  // current wiki formatting will be used
-------------------------------
To include a repository file and format it as markdown or asciidoc:
-------------------------------
{{repo_includemd(file_path)}} <1>

{{repo_includeascii(file_path)}} <1>
-------------------------------
(1) You can use Redmine's linking syntax to link to a file in specific project, repository and/or revision. See section 'Repository files' http://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingRedmineLinks[here].

TODO
----

The macro must be extended for controlling if the Wiki format is applied or not.
Moreover a code block could be also used for code inclusion. Maybe those options
should be added by using another macro name.

Example of additional feature:

-----------------------------------------------
{{repo_include(file_path, revision, is_block)}}
-----------------------------------------------

Known Issues
------------

When using 'repo_includemd' or 'repo_includeascii', linking to a file contained in root of the repository in specific revision or branch doesn't work. Example: '{{repo_includemd(source:file.md@master)}}'

This is caused by a bug in redmine's link parsing, which will recognize the link as two links, one to 'source' and the other one as a mail address 'file.md@master'.

Notes
-----

This plugin is very simple. It SHOULD be enhanced by adding new macros and by
improving the first one.
