Redmine Scmacros
================
Gregory ROMÉ, Mitsuhiro YOSHITANI
v0.2.0, 02-oct-2013

Copyright (C) Orchitech?
Copyright (C) TODO

This plugin provides Wiki macros related to repositories.

License
-------

--------------------------------------------------------------------------------
// TODO change license?
Copyright (C) 2010-2013 Gregory ROMÉ
Copyright (C) 2011 Mitsuhiro YOSHITANI

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
--------------------------------------------------------------------------------

Installation
------------

See the http://www.redmine.org/projects/redmine/wiki/Plugins#Installing-a-plugin[howto] for Redmine plugin installation.

Required
--------

Redmine 1.3.0 or later

Gems for the markup language you wish to include. Put these into the plugin's Gemfile.
For list of gems, see https://github.com/github/markup#markups[here].

Documentation
-------------

To include a repository file:


{{repo_include(file_path)}}

You can use Redmine's linking syntax to link to a file in specific project, repository and/or revision. See section 'Repository files' http://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingRedmineLinks[here].

Known Issues
------------

When using 'repo_includemd' or 'repo_includeascii', linking to a file contained in root of the repository in specific revision or branch doesn't work. Example: '{{repo_includemd(source:file.md@master)}}'

This is caused by a bug in redmine's link parsing, which will recognize the link as two links, one to 'source' and the other one as a mail address 'file.md@master'.
